### PR TITLE
[WIP] codeclimate.yml , editorconfig and other files

### PR DESCRIPTION
**Pull request by programmer4web**
added eslint; script for yarn lint; eslint ignore 'sourcemap' and 'dist' folders.
Some fixes for indentation as spaces to tabs.
const or let instead of var.
eqeqeq fixes.
disabled some eslint rules for demo: no-global-assign, no-use-before-define, no-unused-vars
rebuild done with: yarn prepare.
add basic test with web component tester.
fixes https://github.com/Neovici/nullxlsx/issues/7

### CODE REVIEW

**Comment by programmer4web** [comment]
@nomego I have done some updates for nullxlsx can you take a look and give me some feedback pls or ask for someone to do this instead of you? :)

**Comment by nomego** [comment]
I think you'll have to highlight if there are any actual logic changes or if everything is just addressing eslint/codeclimate errors ?
Tests would be good to merge before this I guess :)

**Comment by programmer4web** [comment]
@nomego Every change is about eslint/codeclimate, no logic changes in this Pull request. I have used the examples in Demo to see if the library exports files as it is supposed; and I have used bower link and it passes the tests in cosmoz-omnitable.  About tests I will see if I can use the demos as starting points for tests.

**Comment by programmer4web** [comment]
@nomego I have added an basic test with web component tester and Pascal enabled this project on Travis-ci and it is passing the tests.

**Comment by nomego** [comment]
Great! Is still WIP? Want to refactor those two dup functions or merge as is?

**Comment by jokedst** [comment]
Oohh cool! Tests!

One bug managed to slip in - an infinite loop if you run nullzip with createFolderEntries = true.
I pushed a fix, although I think the whole createFolderEntries feature should simply be removed... It's not used by our code and I doubt it's actually needed anywhere! That should be a separate pullrequest though.

It would be nice if the readme was updated with instructions how to build and test now (and remove the whole "No automatic tests yet"-part! ;) )

Removing the "dupe" functions is not as straight-forward as it sounds... It uses "this" heavily so would need some inheritance between the classes... Or some js "prototype" magic I have no clue how to write?
Anyway, I say merge as-is and fix that in a separate PR

**Pull request merged**
